package com.niooii;

public enum GameType {
    ONLINEMULTIPLAYER,
    LOCALMULTIPLAYER,
    SINGLEPLAYER,
    SIMULATION_RANDOM,
    MULTISIMULATION_RANDOM,
    SIMULATION_COMPUTER,
    MULTISIMULATION_COMPUTER
}
